#!/bin/sh

EXPECTED=`mesg`
if [ $? -ne 0 ]
then
	echo system mesg failed - possibly in no-tty parallel test mode
	exit 77
fi

OUT=`mesg/mesg`
if [ $? -ne 0 ]
then
	echo T1 failed
	exit 1
fi
if [ "X$OUT" != "X$EXPECTED" ]
then
	echo T2 failed
	exit 1
fi
