.Dd December 2008
.Dt IPCRM 1

.Sh NAME

.Nm ipcrm
.Nd remove an XSI message queue, semaphore set, or shared memory
segment identifier

.Sh SYNOPSIS

.Nm ipcrm
.Ar [ -q msgid | -Q msgkey | -s semid | -S semkey | -m shmid | -M shmkey ] ...

.Sh DESCRIPTION

    The ipcrm utility shall remove zero or more message queues, semaphore
sets, or shared memory segments. The interprocess communication facilities to
be removed are specified by the options.

    Only a user with appropriate privilege shall be allowed to remove an
interprocess communication facility that was not created by or owned by the
user invoking ipcrm.

.Sh OPTIONS

    The ipcrm facility supports the Base Definitions volume of IEEE Std
1003.1-2001, Section 12.2, Utility Syntax Guidelines.

    The following options shall be supported:

    -q  msgid
        Remove the message queue identifier msgid from the system and destroy
the message queue and data structure associated with it.
    -m  shmid
        Remove the shared memory identifier shmid from the system. The shared
memory segment and data structure associated with it shall be destroyed after
the last detach.
    -s  semid
        Remove the semaphore identifier semid from the system and destroy the
set of semaphores and data structure associated with it.
    -Q  msgkey
        Remove the message queue identifier, created with key msgkey, from
the system and destroy the message queue and data structure associated with
it.
    -M  shmkey
        Remove the shared memory identifier, created with key shmkey, from
the system. The shared memory segment and data structure associated with it
shall be destroyed after the last detach.
    -S  semkey
        Remove the semaphore identifier, created with key semkey, from the
system and destroy the set of semaphores and data structure associated with
it.

.Sh OPERANDS

    None.

.Sh STDIN

    Not used.

.Sh INPUT FILES

    None.

.Sh ENVIRONMENT VARIABLES

    The following environment variables shall affect the execution of ipcrm:

    LANG
        Provide a default value for the internationalization variables that
are unset or null. (See the Base Definitions volume of IEEE Std 1003.1-2001,
Section 8.2, Internationalization Variables for the precedence of
internationalization variables used to determine the values of locale
categories.)
    LC_ALL
        If set to a non-empty string value, override the values of all the
other internationalization variables.
    LC_CTYPE
        Determine the locale for the interpretation of sequences of bytes of
text data as characters (for example, single-byte as opposed to multi-byte
characters in arguments).
    LC_MESSAGES
        Determine the locale that should be used to affect the format and
contents of diagnostic messages written to standard error.
    NLSPATH
        Determine the location of message catalogs for the processing of
LC_MESSAGES .

.Sh ASYNCHRONOUS EVENTS

    Default.

.Sh STDOUT

    Not used.

.Sh STDERR

    The standard error shall be used only for diagnostic messages.

.Sh OUTPUT FILES

    None.

.Sh EXTENDED DESCRIPTION

    None.

.Sh EXIT STATUS

    The following exit values shall be returned:

     0
        Successful completion.
    >0
        An error occurred.

.Sh CONSEQUENCES OF ERRORS

    Default.

The following sections are informative.
.Sh APPLICATION USAGE

    None.

.Sh EXAMPLES

    None.

.Sh RATIONALE

    None.

.Sh FUTURE DIRECTIONS

    None.

.Sh SEE ALSO

    ipcs, the System Interfaces volume of IEEE Std 1003.1-2001, msgctl(),
semctl(), shmctl()

