
bin_PROGRAMS += ipcrm/ipcrm

dist_man_MANS += ipcrm/ipcrm.1

ipcrm_ipcrm_SOURCES = ipcrm/ipcrm.cc
ipcrm_ipcrm_LDADD = $(LIBPU) $(ARGP_LIB)
ipcrm_ipcrm_CPPFLAGS = -I$(srcdir)/include

TESTS += ipcrm/ipcrm-test

EXTRA_DIST += ipcrm/ipcrm-test

