#!/usr/bin/perl -w

use strict;

my (%strmap);

&read_input;
&pr_header;
&pr_list;
&pr_footer;
exit(0);

sub read_input {
	while (<>) {
		next if /^\s*$/;
		next if /^#/;
		die "invalid input: $_\n"
			unless /^\s*(\S+)\s+(\w+)\s*$/;

		die "duplicate key '$1'\n"
			if exists $strmap{$1};
		$strmap{$1} = $2;
	}
}

sub pr_list_entry {
	my ($name, $value) = @_;

	printf "\t{ \"%s\",\t\t%s },\n", $name, $value;
}

sub pr_list {
	my ($s);

	foreach $s (sort keys %strmap) {
		pr_list_entry($s, $strmap{$s});
	}
}

sub pr_header {
print <<"EOM";

/*
 * File auto-generated by gen-strmap.pl in the posixutils package.
 * Do not edit.
 */

static struct strmap STRMAP[] = {
EOM
}

sub pr_footer {
print <<"EOM";
	{ NULL, 0 },	/* list terminator */
};

EOM
}

