.Dd December 2008
.Dt MKFIFO 1

.Sh NAME

.Nm mkfifo
.Nd make FIFO special files

.Sh SYNOPSIS

    mkfifo [-m mode] file...

.Sh DESCRIPTION

    The mkfifo utility shall create the FIFO special files specified by the
operands, in the order specified.

    For each file operand, the mkfifo utility shall perform actions
equivalent to the mkfifo() function defined in the System Interfaces volume
of IEEE Std 1003.1-2001, called with the following arguments:

        The file operand is used as the path argument.

        The value of the bitwise-inclusive OR of S_IRUSR, S_IWUSR, S_IRGRP,
S_IWGRP, S_IROTH, and S_IWOTH is used as the mode argument. (If the -m option
is specified, the value of the mkfifo() mode argument is unspecified, but the
FIFO shall at no time have permissions less restrictive than the -m mode
option-argument.)

.Sh OPTIONS

    The mkfifo utility shall conform to the Base Definitions volume of IEEE
Std 1003.1-2001, Section 12.2, Utility Syntax Guidelines.

    The following option shall be supported:

    -m  mode
        Set the file permission bits of the newly-created FIFO to the
specified mode value. The mode option-argument shall be the same as the mode
operand defined for the chmod utility. In the symbolic_mode strings, the op
characters '+' and '-' shall be interpreted relative to an assumed initial
mode of a= rw.

.Sh OPERANDS

    The following operand shall be supported:

    file
        A pathname of the FIFO special file to be created.

.Sh STDIN

    Not used.

.Sh INPUT FILES

    None.

.Sh ENVIRONMENT VARIABLES

    The following environment variables shall affect the execution of mkfifo:

    LANG
        Provide a default value for the internationalization variables that
are unset or null. (See the Base Definitions volume of IEEE Std 1003.1-2001,
Section 8.2, Internationalization Variables for the precedence of
internationalization variables used to determine the values of locale
categories.)
    LC_ALL
        If set to a non-empty string value, override the values of all the
other internationalization variables.
    LC_CTYPE
        Determine the locale for the interpretation of sequences of bytes of
text data as characters (for example, single-byte as opposed to multi-byte
characters in arguments).
    LC_MESSAGES
        Determine the locale that should be used to affect the format and
contents of diagnostic messages written to standard error.
    NLSPATH
        [XSI] [Option Start] Determine the location of message catalogs for
the processing of LC_MESSAGES . [Option End]

.Sh ASYNCHRONOUS EVENTS

    Default.

.Sh STDOUT

    Not used.

.Sh STDERR

    The standard error shall be used only for diagnostic messages.

.Sh OUTPUT FILES

    None.

.Sh EXTENDED DESCRIPTION

    None.

.Sh EXIT STATUS

    The following exit values shall be returned:

     0
        All the specified FIFO special files were created successfully.
    >0
        An error occurred.

.Sh CONSEQUENCES OF ERRORS

    Default.

The following sections are informative.
.Sh APPLICATION USAGE

    None.

.Sh EXAMPLES

    None.

.Sh RATIONALE

    This utility was added to permit shell applications to create FIFO
special files.

    The -m option was added to control the file mode, for consistency with
the similar functionality provided by the mkdir utility.

    Early proposals included a -p option similar to the mkdir -p option that
created intermediate directories leading up to the FIFO specified by the
final component. This was removed because it is not commonly needed and is
not common practice with similar utilities.

    The functionality of mkfifo is described substantially through a
reference to the mkfifo() function in the System Interfaces volume of IEEE
Std 1003.1-2001. For example, by default, the mode of the FIFO file is
affected by the file mode creation mask in accordance with the specified
behavior of the mkfifo() function. In this way, there is less duplication of
effort required for describing details of the file creation.

.Sh FUTURE DIRECTIONS

    None.

.Sh SEE ALSO

    chmod(), umask(), the System Interfaces volume of IEEE Std 1003.1-2001,
mkfifo()

