#!/bin/sh

FILE="uniq/basic-uniq-$$"

uniq/uniq -c "$srcdir/uniq/uniq.data1" > $FILE

if ! cmp -s $FILE "$srcdir/uniq/uniq.data2"
then
	echo "basic uniq test failed"
	rm -f $FILE
	exit 1
fi

rm -f $FILE
exit 0
