#!/bin/sh

OUTFN="asa/asa-test.$$"

asa/asa $srcdir/asa/asa-test.in1 > $OUTFN
if [ $? -ne 0 ]
then
	rm -f $OUTFN
	exit 1
fi

cmp -s $srcdir/asa/asa-test.out1 $OUTFN
retval=$?
rm -f $OUTFN

exit $retval
