#!/bin/sh

TMPFILE="basic-cksum-$$"

rm -f $TMPFILE

../cksum $top_srcdir/tests/test.data | \
	awk -F ' ' '{print $1, $2}' > $TMPFILE

if ! cmp -s $top_srcdir/tests/cksum-test.data $TMPFILE
then
	echo "cksum: comparison failed"
	rm -f $TMPFILE
	exit 1
fi

rm -f $TMPFILE
exit 0
