
bin_PROGRAMS += kill/kill

dist_man_MANS += kill/kill.1

kill_kill_SOURCES = kill/kill.cc
kill_kill_LDADD = $(LIBPU) $(ARGP_LIB)
kill_kill_CPPFLAGS = -I$(srcdir)/include -I$(builddir)/kill

CLEANFILES += kill/kill-siglist.h

TESTS += kill/kill-test

EXTRA_DIST += kill/kill-test kill/gen-siglist.pl

kill/kill-siglist.h: signal-copy.h
	$(AM_V_GEN)$(PERL) $(srcdir)/kill/gen-siglist.pl $(srcdir)/signal-copy.h >$@

kill/kill.cc: kill/kill-siglist.h
