#!/bin/sh

OUTFN="grep/grep-test.out.$$"

grep/grep shall $srcdir/grep/grep.1 > $OUTFN
if [ $? -ne 0 ]
then
	rm -f $OUTFN
	echo T1 failed
	exit 1
fi

cmp -s $srcdir/grep/test1.out $OUTFN
retval=$?
rm -f $OUTFN
if [ $retval -ne 0 ]
then
        echo T2 failed
        exit 1
fi

./grep/grep dummynotfound $srcdir/grep/grep.1
if [ $? -ne 1 ]
then
	echo T3 failed
	exit 1
fi

COUNT=`grep/grep -c shall $srcdir/grep/grep.1`
if [ $? -ne 0 ]
then
	echo T4 failed
	exit 1
fi
if [ $COUNT -ne 40 ]
then
	echo T5 failed
	exit 1
fi

exit 0
