.Dd December 2008
.Dt FALSE 1

.Sh NAME

.Nm false
.Nd return false value

.Sh SYNOPSIS

.Nm false

.Sh DESCRIPTION

The false utility unconditionally returns a non-zero exit code.

.Sh OPTIONS

None.

.Sh OPERANDS

None.

.Sh STDIN

Not used.

.Sh INPUT FILES

None.

.Sh ENVIRONMENT VARIABLES

None.

.Sh ASYNCHRONOUS EVENTS

Default.

.Sh STDOUT

Not used.

.Sh STDERR

Not used.

.Sh OUTPUT FILES

None.

.Sh EXTENDED DESCRIPTION

None.

.Sh EXIT STATUS

The false utility always exits with a value other than zero.

.Sh CONSEQUENCES OF ERRORS

Default.

