.Dd December 2008
.Dt FALSE 1

.Sh NAME

.Nm false
.Nd return false value

.Sh SYNOPSIS

.Nm false

.Sh DESCRIPTION

The false utility unconditionally returns a non-zero exit code.

.Sh OPTIONS

None.

.Sh OPERANDS

None.

.Sh STDIN

Not used.

.Sh INPUT FILES

None.

.Sh ENVIRONMENT VARIABLES

None.

.Sh ASYNCHRONOUS EVENTS

Default.

.Sh STDOUT

Not used.

.Sh STDERR

Not used.

.Sh OUTPUT FILES

None.

.Sh EXTENDED DESCRIPTION

None.

.Sh EXIT STATUS

The false utility always exits with a value other than zero.

.Sh CONSEQUENCES OF ERRORS

Default.

.Sh LEGAL

Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2004 Edition, Standard for Information Technology --
Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2004 by The Institute for
Electrical and Electronics Engineers, Inc and The Open Group. In the
event of any discrepancy between this and the original IEEE and The
Open Group Standard, the original IEEE and The Open Group Standard
is the referee document. The original Standard can be obtained online
at http://www.opengroup.org/unix/online.html
