
.Dd December 2008
.Dt TRUE 1

.Sh NAME

.Nm true
.Nd return true value

.Sh SYNOPSIS

.Nm true

.Sh DESCRIPTION

The true utility returns with exit code zero.

.Sh OPTIONS

None.

.Sh OPERANDS

None.

.Sh STDIN

Not used.

.Sh INPUT FILES

None.

.Sh ENVIRONMENT VARIABLES

None.

.Sh ASYNCHRONOUS EVENTS

Default.

.Sh STDOUT

Not used.

.Sh STDERR

Not used.

.Sh OUTPUT FILES

None.

.Sh EXTENDED DESCRIPTION

None.

.Sh EXIT STATUS

Zero.

.Sh CONSEQUENCES OF ERRORS

None.

