
bin_PROGRAMS += link/link

dist_man_MANS += link/link.1

link_link_SOURCES = link/link.cc
link_link_LDADD = $(LIBPU) $(ARGP_LIB) $(LIBINTL)
link_link_CPPFLAGS = -I$(srcdir)/include

TESTS += link/link-test

EXTRA_DIST += link/link-test

