#!/bin/sh

TMPFILE="sort-test.$$.1"
TMPFILE2="sort-test.$$.2"

./sort $srcdir/test.data > $TMPFILE
if [ $? -ne 0 ]
then
	echo T1.1 failed
	rm -f $TMPFILE
	exit 1
fi

cmp -s $TMPFILE $srcdir/test.t1
retval=$?
rm -f $TMPFILE
if [ $retval -ne 0 ]
then
	echo T1 failed
	exit 1
fi

./sort -r $srcdir/test.data > $TMPFILE
if [ $? -ne 0 ]
then
	echo T2.1 failed
	rm -f $TMPFILE
	exit 1
fi

cmp -s $TMPFILE $srcdir/test.t2
retval=$?
rm -f $TMPFILE
if [ $retval -ne 0 ]
then
	echo T2 failed
	exit 1
fi

./sort -c $srcdir/test.t1
if [ $? -ne 0 ]
then
	echo T3 failed
	exit 1
fi

./sort -r -c $srcdir/test.t1
if [ $? -ne 1 ]
then
	echo T3.1 failed
	exit 1
fi

./sort -r -c $srcdir/test.t2
if [ $? -ne 0 ]
then
	echo T4 failed
	exit 1
fi

./sort -c $srcdir/test.t2
if [ $? -ne 1 ]
then
	echo T4.1 failed
	exit 1
fi

sort -m $srcdir/test.data3-1 $srcdir/test.data3-2 $srcdir/test.data3-3 > $TMPFILE
if [ $? -ne 0 ]
then
	echo T5.1 failed
	rm -f $TMPFILE
	exit 1
fi

./sort -m $srcdir/test.data3-1 $srcdir/test.data3-2 $srcdir/test.data3-3 > $TMPFILE2
if [ $? -ne 0 ]
then
	echo T5.2 failed
	rm -f $TMPFILE $TMPFILE2
	exit 1
fi

cmp -s $TMPFILE $TMPFILE2
retval=$?
rm -f $TMPFILE $TMPFILE2

if [ $? -ne 0 ]
then
	echo T5.3 failed
	exit 1
fi

exit 0
