
bin_PROGRAMS += head/head

dist_man_MANS += head/head.1

head_head_SOURCES = head/head.cc
head_head_LDADD = $(LIBPU) $(ARGP_LIB) $(LIBINTL)
head_head_CPPFLAGS = -I$(srcdir)/include -I$(builddir)/head

TESTS += head/head-test

EXTRA_DIST += head/head-test head/test1.in head/test1.out

