#!/bin/sh

FILE="tsort/basic-tsort-$$"

tsort/tsort "$srcdir/tsort/tsort.data1" > $FILE

if ! cmp -s $FILE "$srcdir/tsort/tsort.data2"
then
	echo "basic tsort test failed"
	rm -f $FILE
	exit 1
fi

rm -f $FILE
exit 0
