#!/bin/sh

FILE1="basic-cmp-$$-1"
FILE2="basic-cmp-$$-2"

DATA1="foo"
DATA2="bar baz"

echo "$DATA1" > $FILE1
echo "$DATA1" > $FILE2

if ! ./cmp -s $FILE1 $FILE2
then
	echo "cmp same failed"
	rm -f $FILE1 $FILE2
	exit 1
fi

echo "$DATA1" > $FILE1
echo "$DATA2" > $FILE2

if ./cmp -s $FILE1 $FILE2
then
	echo "cmp different failed"
	rm -f $FILE1 $FILE2
	exit 1
fi

rm -f $FILE1 $FILE2
exit 0
