#!/bin/sh

TMPFILE="cksum/basic-cksum-$$.1"
TMPFILE2="cksum/basic-cksum-$$.2"

cksum/cksum $srcdir/cksum/test.data | \
	awk -F ' ' '{print $1, $2}' > $TMPFILE
if [ $? -ne 0 ]
then
	echo cksum T1
	rm -f $TMPFILE
	exit 1
fi

cat $srcdir/cksum/test.data | ./cksum/cksum | awk -F ' ' '{print $1, $2}' > $TMPFILE2

cmp -s $srcdir/cksum/cksum-test.data $TMPFILE
retval1=$?
rm -f $TMPFILE

cmp -s $srcdir/cksum/cksum-test.data $TMPFILE2
retval2=$?
rm -f $TMPFILE2

if [ $retval1 -ne 0 ]
then
	echo cksum T2
	exit 1
fi
if [ $retval2 -ne 0 ]
then
	echo cksum T3
	exit 1
fi

cksum/cksum $srcdir/cksum/test.data.no-exist
if [ $? -ne 1 ]
then
	echo cksum T4
	exit 1
fi

cksum/cksum $srcdir/cksum/test.data $srcdir/cksum/test.data2 | \
	awk -F ' ' '{print $1, $2}' > $TMPFILE
if [ $? -ne 0 ]
then
	echo cksum T5
	rm -f $TMPFILE
	exit 1
fi

cmp -s $srcdir/cksum/cksum-test.data2 $TMPFILE
retval=$?
rm -f $TMPFILE
if [ $retval -ne 0 ]
then
	echo cksum T6
	exit 1
fi

exit 0

