.Dd December 2008
.Dt LOGNAME 1

.Sh NAME

.Nm logname
.Nd return the user's login name

.Sh SYNOPSIS

.Nm logname

.Sh DESCRIPTION

    The logname utility shall write the user's login name to standard output.
The login name shall be the string that would be returned by the getlogin()
function defined in the System Interfaces volume of IEEE Std 1003.1-2001.
Under the conditions where the getlogin() function would fail, the logname
utility shall write a diagnostic message to standard error and exit with a
non-zero exit status.

.Sh OPTIONS

    None.

.Sh OPERANDS

    None.

.Sh STDIN

    Not used.

.Sh INPUT FILES

    None.

.Sh ENVIRONMENT VARIABLES

    The following environment variables shall affect the execution of
logname:

    LANG
        Provide a default value for the internationalization variables that
are unset or null. (See the Base Definitions volume of IEEE Std 1003.1-2001,
Section 8.2, Internationalization Variables for the precedence of
internationalization variables used to determine the values of locale
categories.)
    LC_ALL
        If set to a non-empty string value, override the values of all the
other internationalization variables.
    LC_CTYPE
        Determine the locale for the interpretation of sequences of bytes of
text data as characters (for example, single-byte as opposed to multi-byte
characters in arguments).
    LC_MESSAGES
        Determine the locale that should be used to affect the format and
contents of diagnostic messages written to standard error.
    NLSPATH
        [XSI] [Option Start] Determine the location of message catalogs for
the processing of LC_MESSAGES . [Option End]

.Sh ASYNCHRONOUS EVENTS

    Default.

.Sh STDOUT

    The logname utility output shall be a single line consisting of the
user's login name:

    "%s\n", <login name>

.Sh STDERR

    The standard error shall be used only for diagnostic messages.

.Sh OUTPUT FILES

    None.

.Sh EXTENDED DESCRIPTION

    None.

.Sh EXIT STATUS

    The following exit values shall be returned:

     0
        Successful completion.
    >0
        An error occurred.

.Sh CONSEQUENCES OF ERRORS

    Default.

The following sections are informative.
.Sh APPLICATION USAGE

    The logname utility explicitly ignores the LOGNAME environment variable
because environment changes could produce erroneous results.

.Sh EXAMPLES

    None.

.Sh RATIONALE

    The passwd file is not listed as required because the implementation may
have other means of mapping login names.

.Sh FUTURE DIRECTIONS

    None.

.Sh SEE ALSO

    id, who, the System Interfaces volume of IEEE Std 1003.1-2001, getlogin()

