#!/bin/sh

EXPECTED=`tty`
if [ $? -ne 0 ]
then
	echo system tty failed - possibly in no-tty parallel test mode
	exit 77
fi

OUT=`tty/tty`
if [ $? -ne 0 ]
then
	echo T1 failed
	exit 1
fi
if [ "X$OUT" != "X$EXPECTED" ]
then
	echo T2 failed
	exit 1
fi
