
bin_PROGRAMS += dirname/dirname

dist_man_MANS += dirname/dirname.1

dirname_dirname_SOURCES = dirname/dirname.cc
dirname_dirname_LDADD = $(LIBPU) $(ARGP_LIB)
dirname_dirname_CPPFLAGS = -I$(srcdir)/include

TESTS += dirname/dirname-test

EXTRA_DIST += dirname/dirname-test dirname/dirname-tests.json

