
bin_PROGRAMS += time/time

dist_man_MANS += time/time.1

time_time_SOURCES = time/time.cc
time_time_LDADD = $(LIBPU) $(ARGP_LIB) $(LIBINTL)
time_time_CPPFLAGS = -I$(srcdir)/include

TESTS += time/time-test

EXTRA_DIST += time/time-test

