
bin_PROGRAMS += wc/wc

dist_man_MANS += wc/wc.1

wc_wc_SOURCES = wc/wc.cc
wc_wc_LDADD = $(LIBPU) $(ARGP_LIB) $(LIBINTL)
wc_wc_CPPFLAGS = -I$(srcdir)/include

TESTS += wc/wc-test

EXTRA_DIST += wc/wc-test wc/test.data

